### ISSUE TITLE
Sync with GNU/Octave

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qtermwidget#240]
It looks like GNU/Octave maintains a [fork](https://hg.savannah.gnu.org/hgweb/octave/file/af7faef288ad/libgui/qterminal/libqterminal/
) of this widget for the GUI
It would be great to share the code with them
However, it needs us to
- [ ] *Carefully* bring all the bugfixes to this repo
- [ ] Support Windows

Once this is done we can leave a ticket in GNU Savannah for them to use our version
*This post will be updated and enhanced*

**Comment by shlyakpavel** [comment]
As discussed with Octave devs:
Octave GUI does not need >90% of a classic terminal features. The only app it runs is Octave. No positioning, no coloring, no special sequences.. So the most obvious and straightforward thing there is to replace it with a plaintext widget :) This requires much less work and maintaining. Thus, we do not need to care about them

**Comment by yan12125** [comment]
Thank you for proposing the idea to the Octave team! Bringing qterm* to other platforms is still an interesting idea :)

**Comment by apjanke** [comment]
Personally, I would bet that Octave is going to have a hard time switching from QTermWidget to a "plain text" widget. The Octave Command Window is more like a terminal than a plain text document viewer or editor. They may not need 90% of a terminal widget's features, but the 10% that they do need, they really do need, and a plain text editor widget probably won't support them well.

They do need positioning to deal with moving the cursor around the current command line being edited. (And currently, the keyboard shortcuts for navigation there are not working well. That's why I'm hacking on QTermWidget in the first place.) They may need color – it's supported in Matlab's Command Window, highlighting errors in red and hyperlinks in blue. And it should support bracketed paste mode (for differentiating literal tab characters from tab-completion invocations).

Might want to keep this in mind for the future after all.
